spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.github.friday.*.domain.do
  mapper-locations: classpath:com/github/friday/*/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
